Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {C:\Users\Jelmour\Downloads\ResexTester\dist\tcl\tcl8.6.1} C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/library C:/Users/Jelmour/Downloads/library C:/Users/Jelmour/Downloads/tcl8.5.11/library C:/Users/Jelmour/tcl8.5.11/library



This probably means that Tcl wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 27, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1604, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined
Traceback (most recent call last):
  File "mainUI.py", line 27, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1604, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined
Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    {C:\Users\Jelmour\Downloads\ResexTester\dist\tcl\tcl8.6.1} C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/library C:/Users/Jelmour/Downloads/library C:/Users/Jelmour/Downloads/tcl8.5.11/library C:/Users/Jelmour/tcl8.5.11/library



This probably means that Tcl wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tcl8.5/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tk8.5 C:/Users/Jelmour/Downloads/lib/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/library



This probably means that tk wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tcl8.5 C:/Users/Jelmour/Downloads/lib/tcl8.5 C:/Users/Jelmour/Downloads/ResexTester/library C:/Users/Jelmour/Downloads/library C:/Users/Jelmour/Downloads/tcl8.5.11/library C:/Users/Jelmour/tcl8.5.11/library



This probably means that Tcl wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tcl8.5/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tk8.5 C:/Users/Jelmour/Downloads/lib/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/library



This probably means that tk wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 10, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1756, in __init__
_tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
    C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tcl8.5/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/lib/tk8.5 C:/Users/Jelmour/Downloads/lib/tk8.5 C:/Users/Jelmour/Downloads/ResexTester/library

C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/tk.tcl: couldn't read file "C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/listbox.tcl": no such file or directory
couldn't read file "C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/listbox.tcl": no such file or directory
    while executing
"source C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/listbox.tcl"
    (in namespace eval "::" script line 1)
    invoked from within
"namespace eval :: [list source [file join $::tk_library $file.tcl]]"
    (procedure "SourceLibFile" line 2)
    invoked from within
"SourceLibFile listbox"
    (in namespace eval "::tk" script line 4)
    invoked from within
"namespace eval ::tk {
	SourceLibFile button
	SourceLibFile entry
	SourceLibFile listbox
	SourceLibFile menu
	SourceLibFile panedwindow
	SourceLibFile ..."
    invoked from within
"if {$::tk_library ne ""} {
    proc ::tk::SourceLibFile {file} {
        namespace eval :: [list source [file join $::tk_library $file.tcl]]
    }
   ..."
    (file "C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/tk.tcl" line 409)
    invoked from within
"source C:/Users/Jelmour/Downloads/ResexTester/dist/tcl/tk8.5/tk.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $file]"


This probably means that tk wasn't installed properly.

Traceback (most recent call last):
  File "mainUI.py", line 27, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1604, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined
Traceback (most recent call last):
  File "mainUI.py", line 27, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1604, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined
Traceback (most recent call last):
  File "mainUI.py", line 27, in <module>
  File "D:\Python33\lib\tkinter\__init__.py", line 1604, in wm_iconbitmap
_tkinter.TclError: bitmap "icon.ico" not defined
Traceback (most recent call last):
  File "mainUI.py", line 2, in <module>
ImportError: No module named 'libs'
Traceback (most recent call last):
  File "mainUI.py", line 2, in <module>
ImportError: No module named 'libs'
